Add counting leaderboard
ifvictr/jia pull request #2
Opened 2020-11-18 17:48 UTC by cjdenio

This PR adds a slash command (available at http://server/slack/leaderboard) that shows monthly counting stats!

2020-11-19 07:04 UTC, KhushrajRathod approved these changes

2020-11-19 16:22 UTC, ifvictr commented
@cjdenio This is awesome! Do you mind adding a screenshot to this thread so we can get a preview?

2020-11-19 17:03 UTC, cjdenio commented
Of course! Here's how it works:

![image](https://user-images.githubusercontent.com/34525547/99698786-2e2ea280-2a5f-11eb-893a-85faa40fb911.png)

2020-11-21 14:24 UTC, ifvictr requested changes

2020-11-21 14:24 UTC, ifvictr commented on pkg/jia/handlers.go
> +	redisClient.Incr(fmt.Sprintf("leaderboard:%d-%d:%s", month, year, event.User))
Can you change it so that it's YYYY-DD instead?

2020-11-21 14:24 UTC, ifvictr commented on pkg/jia/handlers.go
> +	scan := redisClient.Scan(0, fmt.Sprintf("leaderboard:%d-%d:*", month, year), 10)
Same here

2020-11-21 14:24 UTC, ifvictr commented on pkg/jia/handlers.go
> +	scan_iterator := scan.Iterator()
Use camel case :P

2020-11-21 14:24 UTC, ifvictr commented on pkg/jia/handlers.go
> +		entry_int, err := entry.Int()
Same here!

2020-11-21 14:39 UTC, ifvictr approved these changes

2020-11-21 14:40 UTC, merged

2020-11-21 14:41 UTC, ifvictr commented
Thanks! This feature will be live soon.